# permissions for end users to edit outloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: outloadbalancer-editor-role
rules:
- apiGroups:
  - longyi.longyi.com
  resources:
  - outloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - longyi.longyi.com
  resources:
  - outloadbalancers/status
  verbs:
  - get
